version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: toolbox_api:${DOCKER_TAG:-latest}
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    networks:
      - webnet

networks: 
  webnet:

